#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define GAME_KEY_SEEN 1
#define GAME_KEY_DOWN 2

// View
#define DISPLAY_BUFFER_WIDTH 960.0
#define DISPLAY_BUFFER_HEIGHT 540.0

#define DISPLAY_SCALE 1.0
#define DISPLAY_WIDTH DISPLAY_SCALE *DISPLAY_BUFFER_WIDTH
#define DISPLAY_HEIGHT DISPLAY_SCALE *DISPLAY_BUFFER_HEIGHT

// Player
#define PLAYER_BEGIN_X 180
#define PLAYER_BEGIN_Y 230
#define PLAYER_RADIUS 80
#define PLAYER_IDLE_FRAMES 17

#define PLAYER_MAX_HEALTH 100
#define PLAYER_INIT_SHIELD 0

// Deck
#define DRAW_DECK_X 30
#define DRAW_DECK_Y 400

#define DECK_WIDTH 100
#define DECK_HEIGHT 130

#define MAX_DECK_STACK 20
#define EXTRA_DECK_STACK 33

// Cards
#define CARD_WIDTH 115
#define CARD_HEIGHT 145

#define SPECIAL_DEFAULT_COST 0
#define LIFESTEAL_DEFAULT_COST 3
#define BASE_LIFESTEAL_EFFECT 20
#define BASE_KAIOKEN_BUFF 100
#define DEFAULT_KAIOKEN_COST 3
#define DEFAULT_ENEMY_BUFF_COST 2
#define DEAFULT_INIT_LIFESTEAL 0
#define DEFAULT_BOSS_LIFESTEAL 10
#define CHARGE_HEALTHBAR_BUFF 5
#define CHARGE_ENERGY_BUFF 1

//Health Bar
#define HEALTH_BAR_HEIGHT 20
#define HEALTH_BAR_BACKGROUND_EXTRA 1

#define HEALTH_BAR_RX 0
#define HEALTH_BAR_RY 0

//Player Hand
#define HAND_BEGIN_X 230
#define HAND_BEGIN_Y 440

#define DEFAULT_HAND_STACK 5

// Stamina
#define ENERGY_GAUGE_BEGIN_X   70
#define ENERGY_GAUGE_BEGIN_Y   300
#define ENERGY_GAUGE_RADIUS    30
#define INITIAL_MAX_ENERGY      3

// Charge
#define CHARGE_GAUGE_BEGIN_X    72
#define CHARGE_GAUGE_BEGIN_Y    250
#define CHARGE_GAUGE_RADIUS     72
#define MAX_CHARGES             5

// Enemies
#define DEFAULT_ENEMY_GROUP_SIZE 2
#define BOSS_BATTLE_SIZE 1
#define DEFAULT_BOSS_HAND_SIZE 4

#define ENEMY_BEGIN_X 550
#define ENEMY_BEGIN_Y 120

#define ENEMY_WIDTH 100
#define ENEMY_HEIGHT 100

// View (colors)
#define COLOR_BLACK al_map_rgb(0,0,0)
#define COLOR_WHITE al_map_rgb(255,255,255)
#define COLOR_RED al_map_rgb(255, 0, 0)
#define COLOR_DARK_RED al_map_rgb(192, 3, 3)
#define COLOR_AQUA_BLUE al_map_rgb(105, 237, 255)
#define COLOR_GREY_GREEN al_map_rgb(102, 136, 92)
#define COLOR_YELLOW al_map_rgb(202, 165, 0)
#define COLOR_LIGHT_GREEN al_map_rgb(0, 202, 44)
#define COLOR_GREY_PURPLE al_map_rgb(113, 75, 138)
#define COLOR_GREY al_map_rgb(160, 160, 160)
#define COLOR_FIRE_ORANGE al_map_rgb(255, 101, 11)

#endif
