#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define GAME_KEY_SEEN 1
#define GAME_KEY_DOWN 2

#define DISPLAY_BUFFER_WIDTH 960.0
#define DISPLAY_BUFFER_HEIGHT 540.0

#define DISPLAY_SCALE 1.0
#define DISPLAY_WIDTH DISPLAY_SCALE *DISPLAY_BUFFER_WIDTH
#define DISPLAY_HEIGHT DISPLAY_SCALE *DISPLAY_BUFFER_HEIGHT

#define DRAW_DECK_X 15
#define DRAW_DECK_Y 400

#define DECK_WIDTH 80
#define DECK_HEIGHT 80

#define PLAYER_BEGIN_X 200
#define PLAYER_BEGIN_Y 100
#define PLAYER_RADIUS 100

#define HEALTH_BAR_HEIGHT 20
#define HEALTH_BAR_BACKGROUND_EXTRA 1

#define HEALTH_BAR_RX 0
#define HEALTH_BAR_RY 0

#define HAND_BEGIN_X 350
#define HAND_BEGIN_Y 330

#define CARD_WIDTH 120
#define CARD_HEIGHT 170

// You might want to use this.
typedef enum
{
  MOVE_LEFT = 0,
  MOVE_RIGHT = 1,
} CursorMovementDirection;

#endif